### ISSUE TITLE
Create `.kaz` Kazam parser

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#15]
### Description

Create a Parser to read `.kaz` files.

### Acceptance Criteria

- the `parse` method has to return valid [Kaz ast](https://github.com/bywhitebird/kazam/blob/064d56b452e70c5c7c30fcfc9f1b921daf5ca73d/packages/kaz-file-parser/src/types/KazAst.ts) from the input

### Tasks

- [x] create a `ParserKaz` class that extends `ParserBase`
- [x] implement the `load` method
- [x] implement the `parse` method
- [x] write unit tests for the `parse` method to test the generated AST
