### ISSUE TITLE
Create the `kazam` package

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#18]
### Description

Create the `kazam` package, which will serve to build a Kazam project. It is shipped as a CLI, but also as a package so a project can be built programmatically. It is what will connect Kazam Parsers to Kazam Transformers.

### Acceptance Criteria

- export a `generate` function that will read the config
- the config:
  - should be a `kazam.config.[t|j]s` file
  - could be defined with a `defineConfig` function
  - should accept:
    - a `input` property (a list of string readable by `ParserBase.load`)
    - a `output` property (a string)
    - a `parsers` property (a list of object that extends of ParserBase)
    - a `transformers` property (a list of object that extends of [`TransformerBase`](https://github.com/bywhitebird/kazam/tree/064d56b452e70c5c7c30fcfc9f1b921daf5ca73d/packages/transformer-base))
- ship a CLI
  - should have a global `-c, --config <path>` option to pass the config of the Kazam config
  - should have a `generate` command

### Tasks

 - [x] create the `defineConfig` function
 - [x] create the `generate` function
 - [x] create the CLI
