### ISSUE TITLE
Create Vue 3 transformer

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#29]
### Description

Create a Transformer to generate Vue 3 files.

### Acceptance Criteria

- the transform method has to return valid Vue 3 files (.vue) from the input

### Tasks

- [ ] create a `TransformerVue` class that extends `TransformerBase`
- [ ] implement the `transform` method
- [ ] write unit tests for the `transform` method to test the generated Vue files for each supported entity
