### ISSUE TITLE
Create a tester for web transformers

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#30]
### Description

Create a function that will test transformers aimed at generating HTML code (React, Vue, Svelte, etc.).

### Acceptance Criteria

- the test function must be in its own package (`test-web-transformer`?)
- the test function must return `true` if all tests pass, otherwise `false`
- the test function should test **visually** the rendered HTML code
- the test function should accept two parameters:
  - `transformer` that extends `TransformerBase`
  - `renderHtml` which is a function that takes the `transformer` output and returns a single HTML file
- the test function must execute defined flows, take screenshots and compare them with the screenshots already included

### Tasks

- [x] create a `testWebTransformer` function
- [x] create fixtures
  - [x] simple rendering
  - [x] expression rendering (e.g. `<>{color}</>`)
  - [x] content rendered in a loop
  - [x] auto import components
  - [x] passing props to component
  - [x] passing attributes to html tag (`style="color: red"`?)
  - [x] reactivity
    - [x] state change
    - [x] click event
    - [x] computed properties
    - [x] conditionally rendered content
    - [x] watchers
