### ISSUE TITLE
Create react transformer

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#4]
### Description

Create a Transformer to generate React files.

### Acceptance Criteria

- the `transform` method has to return valid React files (`.tsx`) from the input

### Tasks

- [x] create a `TransformerReact` class that extends `TransformerBase`
- [x] implement the `transform` method
  - [x] support for each entities:
    - [x] attribute
    - [x] component
    - [x] computed
    - [x] content
    - [x] event
    - [x] expression
    - [x] props
    - [x] state
    - [x] statement
    - [x] watcher
- [x] write unit tests for the `transform` method to test the generated React files for each supported entity
