### ISSUE TITLE
Initialize Alakazam

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#46]
**Tasks**
 - [x] initialize a Nuxt project
 - [x] ~use `tsx` files~ (support for `.tsx` files in Volar does not seem to work very well, we will use `.vue` files)
 - [x] initialize panda-css (https://panda-css.com/docs/installation/nuxt)
 - [x] do not use file-based router (https://theroadtoenterprise.com/blog/how-to-setup-custom-routing-in-nuxt-3)
 - [x] import `@whitebird/ui` components
 - [x] use the `@whitebird/ui` panda preset
