### ISSUE TITLE
Add support for `onMount` instruction

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#53]
### Description

We should be able to run function when the component is mounted.

### Acceptance Criteria

- Add support in `kaz-ast`
- Add support in all transformers
- Add tests

### Tasks

- [x] Add support for `onMount` in `kaz-ast`
- [x] Transpile `onMount` to `useEffect(() => {}, [])` in `transformer-react`
- [x] Transpile  `onMount` to `onMounted(() => {})` in `transformer-vue`
- [x] Add typing in `transformer-typescript`
- [x] Add test in `tests-web-transformer`

### Additional Information

The AST should be represented as follows:
```json
{
  "instructions": [
    {
      "$type": "lifecycleEvent",
      "on": "mount",
      "callback": ...
    },
  ],
}
```

The syntax should look like this:
```kaz
- onMount () {
  <code>
}
```
