### ISSUE TITLE
Bad expression transformation in Vue

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#67]
### Current behavior

The TransformerVue does not transform correctly the expressions.

<table>
<tr>
<td> Original </td> <td> Generated </td>
</tr>
<tr>
<td>

```ts
(e) => {
    _value = e.target.value
    onChange(e.target.value)
}
```

</td>
<td>
    
```ts
(((() => ref(e).value)())) => {
    _value.value = ((() => ref(e.target.va((() => ref(lue).val).v((() => ref(a).value)())lue)())ue)())
    ((() => ref(onChange).value)())(((() => ref(e.target.va((() => ref(lue).val).v((() => ref(a).value)())lue)())ue)()))
}
```

</td>
</tr>
</table>

### Solution

We need to improve expression parsing. To facilitate the integration in all transformers, we can implement the transformations on the parser side. Because the specs change according to the targeted framework, library, language, we can add magic strings that are easily replaceable in transformers.

Because we directly have access to the full Kaz AST, the parsing can be very precise. Thus, the generated code should look like this:
```ts
(e) => {
    _value.value = e.target.value
    onChange(e.target.value)
}
```

### Tasks

- [x] Create the `transform-utils` package that contains the magic strings
- [x] Implement the magic strings on the parser side
  - [x] state setter
  - [x] state getter
  - [x] computed getter
- [x] Implement the magic strings replacement on the transformer side
  - [x] TransformerVue
  - [x] TransformerReact
  - [x] TransformerTypescript

### Additional information

The magic string should follow this format `GUID_parameter1base64&parameter2base64...`.
