### ISSUE TITLE
Create Alakazam Live Component

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#71]
**Description**

Alakazam Live Components should generate components (in Kaz AST format) that will fetch the component, and then transform the component to targets (using Kazam).

**Tasks**

- [ ] Create the Alakazam Live Component API endpoints
  _It is in charge to return a script that will render the component at client-side._
- [ ] Create the `Preact`+`htm` transformer
  _Use it to render the component at client side because it is very lightweight (3kb + 0.5kb)._
- [ ] Create the service worker

---

**Example 1:** _(see the PoC working on Glitch: https://glitch.com/edit/#!/jagged-magic-cheetah)_

_This is the component generated by Alakazam Live Component:_
```tsx
import React, { useRef, useEffect } from 'react'

const Component = ({ text }: { text: string }) => {
  const elementRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!elementRef.current) {
      return
    }

    const abortController = new AbortController()

    await fetch(
      `https://alakazam.io/project-id/component-id?${new URLSearchParams({ text })}`,
      { signal },
    )
      .then((response) => response.text())
      .then((liveComponentSource) => {
        const liveComponent = new DOMParser().parseFromString(
          liveComponentSource,
          "text/html"
        ).body.firstChild as HTMLDivElement;

        elementRef.current.replaceWith(liveComponent);
        
        // Force running scripts
        liveComponent.querySelectorAll("script").forEach((script) => {
          const newScript = document.createElement("script");
          script.getAttributeNames().forEach((name) => {
            newScript.setAttribute(name, script.getAttribute(name)!);
          });
          newScript.innerHTML = script.innerHTML;

          liveComponent.removeChild(script);
          liveComponent.appendChild(newScript);
        });
      })

    return () => {
      abortController.abort()
    }
  }, [elementRef])

  return <alakazam-component ref={elementRef} />
}
```

_This is a PoC of an implementation of the API endpoint:_
```ts
export default async function (parameters: Record<string, string>) => {
  const id = Math.random().toString(36).substring(2, 9);

  // TODO: replace `const Component = ...` by the component generated by Kazam (with the `Preact`+`htm` transformer)
  return `
    <alakazam-component style="display: contents;" uid="${id}">
      <script type="module">
        import { h, render } from 'https://esm.sh/preact';
        import { useState, useCallback } from 'https://esm.sh/preact/hooks';
        import htm from 'https://esm.sh/htm/mini';

        // Initialize htm with Preact
        const html = htm.bind(h);

        const Component = (props) => {
          const [state, setState] = useState(0);

          const increment = useCallback(() => {
            console.log('increment')
            setState((state) => state + 1)
          }, [setState]);

          const decrement = useCallback(() => {
            setState((state) => state - 1)
          }, [setState]);

          return html\`<h1>
            \${props.text}
            \${state}
            <button onClick=\${increment}>+</button>
            <button onClick=\${decrement}>-</button>
          </h1>\`;
        }

        render(h(() => Component(${JSON.stringify(
          parameters
        )})), document.querySelector('alakazam-component[uid="${id}"]'));
      </script>
    </alakazam-component>
  `;
}
```

---

**Example 2:** _(see the PoC working on Glitch: https://glitch.com/edit/#!/ebony-remarkable-cymbal)_

This version returns only a script as string.
