### ISSUE TITLE
Manage project creation

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#73]
### Description

At the core of Alakazam is projects, which is in orgs and define which parsers/transformers use and which components transform.

### Tasks

- [x] Initialize EdgeDB database
- [x] Create the database schema
- [x] Create all necessary pages
  - [x] List organizations
  - [x] Organization creation
  - [x] See single organization
  - [x] Configure organization (rename)
  - [x] List projects
  - [x] Project creation
  - [x] Configure project (rename and choose Github repository)

### Additional informations

Here is a non-exhaustive diagram representing the relationships to create and implement:
```
      Organizations◄───Users
            │
            ▼
         Projects◄────Repository
            │
     ┌──────┴─────┐
     ▼            ▼
Transformers    Parsers
```
