### ISSUE TITLE
Manage listening GitHub repository

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#74]
### Description

Alakazam needs to update the generated components on the fly. We can use GitHub webhooks to achieve this.

### Tasks

- [x] Add webhook creation to the project's GitHub repository (see [API documentation](https://docs.github.com/en/rest/repos/webhooks?apiVersion=2022-11-28#create-a-repository-webhook))
- [x] Create a route that does nothing except that it exists to handle the webhook (we will implement the component transformation in #75)
- [x] Add or modify a script to tunnel to the development server (because GitHub webhooks could not access the localhost server)
