### ISSUE TITLE
Manage component transformation in Alakazam

### ISSUE THREAD

**Issue by arthur-fontaine** [bywhitebird/kazam#75]
### Description

Transform the components found in a repository.

### Tasks

- [x] Add a `Root directory` setting to projects
- [x] Add metadata to parsers (to get the extensions)
- [x] Create a function to get the parsers and the transformers from the database entries
- [x] Find the components in a repository
- [x] Use `kazam` to generate the components
- [x] Cache them in the database
- [x] Add a download button that packages the components into a .zip file
